### ISSUE TITLE
Adding module

### ISSUE THREAD

**Issue by rkdm91** [joaohf/meta-erlang#17]
Hello,

I want to add a module ( os-mon ) to my Erlang installation .
I have edited generate-manifest file in scripts/erlang : 

    m.addPackage("${PN}", "",
                 "${PN}-erts ${PN}-kernel ${PN}-stdlib ${PN}-sasl ${PN}-os-mon", "", True)

and launch the script so the file erlang-20.0.5-manifest.inc has been modified.

After building the project i can't find the module in usr/lib/erlang/lib/ : 
~/oe-core-v2/deploy/images/colibri-imx6/Colibri-iMX6_LXDE-Image_2.8.2/rootfs/usr/lib/erlang/lib$ ls
kernel-5.3.1  sasl-3.0.4  stdlib-3.4.1

Do you know how i could add a module, is it the correct procedure ?

**Comment by rkdm91** [comment]
Solved, after rebuilding all the image.

**Comment by joaohf** [comment]
Hi, 

Editing manifest is not the usual way to proceed. See issue #16 

Maybe in local.conf add:

 IMAGE_INSTALL_append = " erlang-os-mon"

Or create a specific packagegroup.
