### ISSUE TITLE
rebar3 class include-erts and system_libs

### ISSUE THREAD

**Issue by asabil** [joaohf/meta-erlang#24]
Hi,

Looking at the rebar3 class, it doesn't seem like the `--include-erts ...` and the `--system_libs ...` are not currently passed to the `rebar3 tar`?

I would like to create an embedded release, and without these flags, erts wouldn't be included. How would you suggest to create an embedded release using this layer? Also taking into consideration that the build host arch <> target host arch.

Thanks

**Comment by joaohf** [comment]
Hi asabil,

Great question!

I have some examples about how to handle it. Unfortunately it needs some update (I think that rebar3 has other ways to do it now).

So check it:

1) https://github.com/joaohf/axon
2) https://github.com/joaohf/axon/blob/master/rebar.config.script
3) https://github.com/joaohf/meta-axon/blob/master/recipes-extended/axon/axon_git.bb

axon (1) is an normal erlang application which uses the rebar.config.script (2) to detect the cross-compiling variables (https://github.com/joaohf/meta-erlang/blob/master/classes/rebar3.bbclass#L14). And (3) is the recipe.

I need to update all these stuffs and provide a better example.

Thanks.

**Comment by joaohf** [comment]
Hi,

Check this out http://joaohf.github.io/meta-erlang/#/

Feel free to reopen this issue.

**Comment by asabil** [comment]
I have looked at the solution, and I am not particularly found of having the packaged software deal with setting the correct include-erts and system_libs itself, especially the rebar3 has native support for passing those through the command line.

Would you accept a PR that changes the rebar3 class do_install task to use `--include-erts` and `--system_libs` ?

Thanks,
Ali

**Comment by joaohf** [comment]
@asabil 

My current approach is to have a rebar.config.script that reads REBAR3_TARGET_INCLUDE_ERTS and REBAR3_TARGET_SYSTEM_LIBS (https://github.com/joaohf/axon/blob/3baebb418f6024aeb221b79fd65f820f8968dd8e/rebar.config.script).

Of course it is better passing these parameters using command line. 

Feel free to submit a PR.

**Comment by joaohf** [comment]
I'm closing this. Feel free to reopen if need.
