### ISSUE TITLE
Erlang Make utility doesn't seem to be included.

### ISSUE THREAD

**Issue by mbsmith** [joaohf/meta-erlang#3]
Was trying to do some live development for testing and found I couldn't compile some applications due to the following error:

escript: exception error: undefined function make:files/2

I can't see anything in the bb file that would prevent this from being included.

**Comment by joaohf** [comment]
Hi mbsmith,

 'erlang-tools' aren't installed by default. Could you install 'erlang-tools' package? Like this:

IMAGE_INSTALL_append = " erlang erlang-tools "

**Comment by mbsmith** [comment]
Ah I didn't notice that it was split up like that.  Including that and a few other packages fixed my issue.

Thanks!

**Comment by bsingh** [comment]
Yes..Thanks  joaohf ,  installing erlang-tools did the trick.
