### ISSUE TITLE
Erlang 22.1

### ISSUE THREAD

**Issue by asabil** [joaohf/meta-erlang#30]
Hi,

Are there any plans to update the Erlang/OTP release to 22.1 ?

Thanks

**Comment by joaohf** [comment]
Hi @asabil,

Sure, there are plans. Check this https://github.com/joaohf/meta-erlang/pull/31

I need to fix a issue regarding to wx and opengl. One of my patches to disable wx is not working. Now is time to fix it using another approach.

**Comment by asabil** [comment]
Ok, thank you for the update. I will have a look, I might be able to help with the patch.
