### ISSUE TITLE
How do I install version 22 OTP?

### ISSUE THREAD

**Issue by dayanola** [joaohf/meta-erlang#34]
Hi, 
I wish to use erlang 22 OTP. 
What should I change in the recipes? 

Thanks,
Amit

**Comment by joaohf** [comment]
Hi @dayanola.

You don't need to change a recipe. This layer has OTP 22.1.7. bitbake will get the most high erlang version, which is 22.1.7.

But if you like to configure it, then:

Add to you 'conf/local.conf'

PREFERRED_VERSION_erlang = "22%"

or 

PREFERRED_VERSION_erlang = "22.1.7"

See: https://www.yoctoproject.org/docs/2.7.1/mega-manual/mega-manual.html#var-PREFERRED_VERSION

Thanks.
