### ISSUE TITLE
Installing dependecies 

### ISSUE THREAD

**Issue by dayanola** [joaohf/meta-erlang#40]
Hi, 
I have installed erlang , elixir and mix like this:
IMAGE_INSTALL_append = " erlang elixir elixir-mix"

There were errors installing Hex about inets, so I've added:

IMAGE_INSTALL_append = " erlang elixir elixir-mix **erlang-inets erlang-tools** "

Now there are errors about ssl. I read somewhere that you can install erlang-ssl, erlang-crypto , etc.

My question is : is there one recipe to add that will install of all these ? I thought erlang-tools will do the trick, but I'm still getting the SSL error:
no match of right hand side value: {:error, {:ssl, {'no such file or directory', 'ssl.app'}}}

Thanks,
Amit

**Comment by dayanola** [comment]
OK, 
I've built an image with:
IMAGE_INSTALL_append = " erlang elixir elixir-mix erlang-inets erlang-tools erlang-ssl erlang-crypto openssl"
And now I get :

no match of right hand side value: {:error, {:public_key, {'no such file or directory', 'public_key.app'}}}

**Comment by joaohf** [comment]
Hi @dayanola,

The `erlang` package will install: kernel, erts, stdlib and sasl (https://github.com/joaohf/meta-erlang/blob/master/recipes-devtools/erlang/erlang-22.1.8-manifest.inc#L1409)

In your IMAGE_INSTALL_append, you can add the erlang-public_key.

I use to start with erlang-modules (https://github.com/joaohf/meta-erlang/blob/master/recipes-devtools/erlang/erlang-22.1.8-manifest.inc#L1413) and then once the application is working I start to remove the unnecessary erlang packages.

**Comment by dayanola** [comment]
thank you.

I also needed erlang-modules-dev and packagegroup-core-buildessential.

In one of the error message, is was suggested I install erlang-dev. Is this different than erlang-modules-dev?

**Comment by joaohf** [comment]
If you are planning to do any kind of development which uses any erlang include files then you should add erlang-modules-dev.

Hmm, currently erlang-dev (https://github.com/joaohf/meta-erlang/blob/master/recipes-devtools/erlang/erlang-22.1.8-manifest.inc#L1394) does not install erlang-erts-dev erlang-kernel-dev erlang-stdlib-dev and erlang-sasl-dev. For now, you should add those packages to IMAGE_INSTALL_append too.

I will fix that because erlang-dev should install those packages automatically.

**Comment by dayanola** [comment]
OK, thanks.
I have added rebar3 to the list, but it is not detected 
_Could not find "rebar3", which is needed to build dependency :ranch
I can install a local copy which is just used by Mix_

Any idea if what is needed other than adding rebar3 to IMAGE_INSTALL_append ?

**Comment by dayanola** [comment]
Also, is there a way to install Hex?

**Comment by joaohf** [comment]
Hi @dayanola 

I guess that I never tried to do a development on the target. This is not my normal workflow. But if you get a working elixir (iex) and erlang (erl), I don't see any problem doing that.

Of course, mix will try to install a rebar3, if not installed. Also mix will try to install hex too. 

Have you included the rebar3 to IMAGE_INSTALL_append ? If yes, what is the return of the `which rebar3`, when running the command in the target image ? 

These are the recipes that I use to test a erlang and elixir applications:


Erlang application recipe:

https://github.com/joaohf/meta-axon/blob/master/recipes-extended/eclero/eclero_git.bb

https://github.com/joaohf/eclero/blob/master/rebar.config
https://github.com/joaohf/eclero/blob/master/rebar.config#L41


Elixir application recipe:

https://github.com/joaohf/meta-axon/blob/master/recipes-extended/axon/axon-scenic_git.bb
https://github.com/joaohf/axon-scenic/blob/master/mix.exs

PS:

Do you use buildhistory ?
Adding the above config into local.conf
INHERIT += "buildhistory"
BUILDHISTORY_COMMIT = "1"

Yocto will create a git repository and is easy to check what packages were installed (https://www.yoctoproject.org/docs/2.7/dev-manual/dev-manual.html#maintaining-build-output-quality)

**Comment by joaohf** [comment]
I'm closing this. Feel free to reopen if need.
