### ISSUE TITLE
RabbitMQ - Missing Dependency

### ISSUE THREAD

**Issue by befedo** [joaohf/meta-erlang#49]
Hi there,
I've simply build `rabbitmq-server` with bitbake.

When running on the target I get:
```{bash}
# /usr/bin/rabbitmq-server

BOOT FAILED
===========

Config file generation failed:
escript: Failed to open file: /usr/bin/cuttlefish
In case the setting comes from a plugin, make sure that the plugin is enabled.
Alternatively remove the setting from the config.

{"init terminating in do_boot",generate_config_file}
init terminating in do_boot (generate_config_file)

Crash dump is being written to: /var/log/rabbitmq/erl_crash.dump...
```

Looks like `cuttlefish` is missing in the dependencies, and I couldn't find it anywhere (neither a receipe).

Has anyone made the same observation?

Thanks for your time and best regards
Befedo

**Comment by joaohf** [comment]
Hello @befedo 

Good catch. I forgot to test rabbitmq using any configuration file :(

![Screenshot_2020-05-28_18-52-23](https://user-images.githubusercontent.com/278690/83170260-8de16c00-a114-11ea-8bb5-5343461220ea.png)

**Comment by befedo** [comment]
Hey @joaohf,

Thanks for the quick response and fix!

**Comment by befedo** [comment]
Hi there,
using the systemd `rabbitmq-server.service` file there seems to be some other dependency missing.
```{text}
Jun 02 10:51:35 intel-corei7-64 rabbitmq-server[5765]: Failed to start socat error:enoent
```
And it looks like `socat` is used for signaling to systemd, thus the service get's killed after a timeout from systemd. After adding socat the signaling to systemd works:
```{text}
Jun 02 10:59:14 intel-corei7-64 systemd[1]: Started RabbitMQ broker.
```
Can anyone confirm this?

Thanks for your time and best regards.
befedo

**Comment by joaohf** [comment]
Yes, I can confirm that.

rabbitmq tries to load sd_notify module (https://github.com/systemd/erlang-sd_notify) and falls back to socat, see https://github.com/rabbitmq/rabbitmq-server/blob/master/apps/rabbitmq_prelaunch/src/rabbit_boot_state_systemd.erl#L45

Adding socat (https://layers.openembedded.org/layerindex/recipe/5109/) recipe to the image will fix the problem.

There is also another approach as described here: http://erlang.org/pipermail/erlang-questions/2018-July/096067.html and https://gist.github.com/maxlapshin/01773f0fca706acdcb4acb77d91d78bb

I'm planning to add socat as dependency.

**Comment by joaohf** [comment]
Added socat as rdepends, when using systemd. 

https://github.com/joaohf/meta-erlang/commit/232551cc2040c7c1e43f2215a257cb3e72e83381
