### ISSUE TITLE
erlang build error in arm 64bit

### ISSUE THREAD

**Issue by chbae** [joaohf/meta-erlang#5]
**Build Environment**
MACHINE: dragonboard-410c
Poky: jethro branch
meta-qcom: jethro branch

I got the below error in arm 64bit

`ERROR: debugedit failed with exit code 256 (cmd was '/home/changhyeok.bae/work/ivi/genivi/gdp_dragon/gdp-src-build/tmp/sysroots/x86_64-linux/usr/lib/rpm/bin/debugedit' -b '/home/changhyeok.bae/                                            work/ivi/genivi/gdp_dragon/gdp-src-build/tmp/work/aarch64-poky-linux' -d '/usr/src/debug' -i -l '/home/changhyeok.bae/work/ivi/genivi/gdp_dragon/gdp-src-build/tmp/work/aarch64-poky-linux/erlang                                            /18.2.3-r0/debugsources.list' '/home/changhyeok.bae/work/ivi/genivi/gdp_dragon/gdp-src-build/tmp/work/aarch64-poky-linux/erlang/18.2.3-r0/package/usr/lib/erlang/lib/runtime_tools-1.9.2/priv/obj                                            /dyntrace.o'):
/home/changhyeok.bae/work/ivi/genivi/gdp_dragon/gdp-src-build/tmp/sysroots/x86_64-linux/usr/lib/rpm/bin/debugedit: /home/changhyeok.bae/work/ivi/genivi/gdp_dragon/gdp-src-build/tmp/work/aarch64                                            -poky-linux/erlang/18.2.3-r0/package/usr/lib/erlang/lib/runtime_tools-1.9.2/priv/obj/dyntrace.o: Unhandled relocation 258 in .debug_info section
ERROR: Function failed: split_and_strip_files
ERROR: Logfile of failure stored in: /home/changhyeok.bae/work/ivi/genivi/gdp_dragon/gdp-src-build/tmp/work/aarch64-poky-linux/erlang/18.2.3-r0/temp/log.do_package.14994
ERROR: Task 3649 (/home/changhyeok.bae/work/ivi/genivi/gdp_dragon/gdp-src-build/../meta-erlang/recipes-devtools/erlang/erlang_18.2.3.bb, do_package) failed with exit code '1'
`

**Comment by bboozzoo** [comment]
Might be RPM's `debugedit` doing something funky. Can you try building without `pacakge_rpm` in `PACKAGE_CLASSES`?

**Comment by joaohf** [comment]
Hi, 

Using:

Build Configuration:
BB_VERSION        = "1.28.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "Ubuntu-15.10"
TARGET_SYS        = "aarch64-poky-linux"
MACHINE           = "dragonboard-410c"
DISTRO            = "poky"
DISTRO_VERSION    = "2.0.2"
TUNE_FEATURES     = "aarch64"
TARGET_FPU        = ""
meta              
meta-yocto        
meta-yocto-bsp    = "jethro:ddbc13155f4db5d98976dc93b586c0be4fc740d1"
meta-qcom         = "jethro:505f490caf66deeb8ae4e8038a2546a8e0c7aca4"
meta-erlang       = "jethro:8878361e26aee0624385a4ef1ede44cdacd8108a"

And rpm in PACKAGE_CLASS, I can't reproduce it. 

@chbae, could you check if I was using the correct SHA's layer?

**Comment by chbae** [comment]
I'm using GDP and below is my environments.

Build Configuration:
BB_VERSION        = "1.28.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "Ubuntu-12.04"
TARGET_SYS        = "aarch64-poky-linux"
MACHINE           = "dragonboard-410c"
DISTRO            = "poky-ivi-systemd"
DISTRO_VERSION    = "10.0.0"
TUNE_FEATURES     = "aarch64"
TARGET_FPU        = ""
meta
meta-yocto
meta-yocto-bsp    = "HEAD:fc45deac89ef63ca1c44e763c38ced7dfd72cbe1"
meta-ivi
meta-ivi-bsp      = "HEAD:9d72380c1d50d0c3469b85c3a43fe612b5ee1dd9"
meta-oe
meta-filesystems
meta-ruby         = "HEAD:ad6133a2e95f4b83b6b3ea413598e2cd5fb3fd90"
meta-qt5          = "HEAD:90919b9d86988e7da01fa2c0a07246b5b5600a5d"
meta-genivi-dev   = "feature/dragon:031df411a10942fb556aaa3657a049fb368ed734"
meta-rust         = "HEAD:f13ac9d48ae928b761d7be204fa8f877d41e7099"
meta-oic          = "HEAD:69146eaf8bc05c74c377e731b7e16d82854a4659"
meta-erlang       = "HEAD:4d7eacc8e6593934ed5b0c8abc3d3e9dc339d849"
meta-rvi          = "HEAD:de9d548fe35e2cee8688faaae910b4f6f7fea17e"
meta-qcom         = "jethro:505f490caf66deeb8ae4e8038a2546a8e0c7aca4"

**Comment by chbae** [comment]
@bboozzoo I tried to remove rpm package but same errors.

**Comment by chbae** [comment]
I successfully built with Ubuntu-14.04 64bit. So I closed this issue.
Sorry and Thanks.
