### ISSUE TITLE
OTP 23 - Any plans to add?

### ISSUE THREAD

**Issue by fnchooft** [joaohf/meta-erlang#51]
Hi Joao, are there any plans to add OTP 23?

**Comment by joaohf** [comment]
Hello Fabian!

I've started the first round. I hope until next weekend I can release something.

**Comment by fnchooft** [comment]
That is great news! Thanks - greetings from Campinas/Polis.
Kind regards,
Fabian

**Comment by joaohf** [comment]
Hi @fnchooft 

I've add erlang 23. Feel free to reopen this in case of any problem.

**Comment by fnchooft** [comment]
Great news - will be testing next week. Kind regards,
Fabian
